/* DUST local artist library. Original image bytes are stored in IndexedDB. */
(()=>{'use strict';
const $=id=>document.getElementById(id), uid=()=>crypto.randomUUID(), versions=['4.5','5'];
const MIME=new Set(['image/png','image/jpeg','image/webp','image/gif','image/avif']);
let db, entries=[], version='4.5', draft=null, pending=null, busy=false, imageReads=0, viewerId=null;
let urls=[]; const positions=new Map();
const message=(text)=>{const el=$('toast');el.textContent=text;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2000);};
const errorText=e=>e?.name==='QuotaExceededError'?'브라우저 저장 공간이 부족함 · 백업 후 불필요한 이미지를 정리해 주세요':e?.message||'저장 작업을 완료하지 못했습니다';
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('dust_artist_plus_v1:'+new URL('./',location.href).pathname,1);req.onupgradeneeded=()=>req.result.createObjectStore('entries',{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);req.onblocked=()=>{$('plusError').textContent='다른 DUST 창을 닫고 다시 열어 주세요';};});}
function readAll(){return new Promise((resolve,reject)=>{const t=db.transaction('entries','readonly'),req=t.objectStore('entries').getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
function write(action){return new Promise((resolve,reject)=>{const tx=db.transaction('entries','readwrite');tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error||new Error('저장이 취소되었습니다'));tx.onerror=()=>{};try{action(tx.objectStore('entries'));}catch(e){tx.abort();reject(e);}});}
function lock(value){busy=value;for(const id of ['plusAdd','plusExport','plusImport','plusMerge','plusReplace','plusImportCancel'])$(id).disabled=value;}
function objectURL(blob){const url=URL.createObjectURL(blob);urls.push(url);return url;}
function button(text,cls,action,label){const b=document.createElement('button');b.type='button';b.className=cls;b.textContent=text;if(label)b.setAttribute('aria-label',label);b.onclick=action;return b;}
function selected(id){return entries.find(e=>e.id===id);}
function imageAt(entry){const i=(positions.get(entry.id)||0)%entry.images.length;return {i,image:entry.images[i]};}
function rotate(id,delta){const e=selected(id);if(!e)return;positions.set(id,((positions.get(id)||0)+delta+e.images.length)%e.images.length);const card=$('plusGrid').querySelector(`[data-id="${id}"]`);if(card){const {i,image}=imageAt(e);card.querySelector('img').src=objectURL(image.blob);card.querySelector('.plus-index').textContent=`${i+1} / ${e.images.length}`;}if(viewerId===id&&$('plusViewer').open)showViewerImage();}
function render(){if($('plusViewer').open)$('plusViewer').close();urls.forEach(URL.revokeObjectURL);urls=[];const grid=$('plusGrid');grid.replaceChildren();const q=$('plusSearch').value.trim().toLocaleLowerCase();const all=entries.filter(e=>e.version===version);const list=all.filter(e=>e.tag.toLocaleLowerCase().includes(q)).sort((a,b)=>b.createdAt-a.createdAt);
$('plusCount').textContent=`${version} · ${list.length}명${q?' / 전체 '+all.length+'명':''} · 이미지 ${list.reduce((n,e)=>n+e.images.length,0)}장`;
if(!list.length){const empty=document.createElement('div');empty.className='plus-empty';empty.textContent=q?'검색 결과가 없음':`${version}에 등록된 작가가 없음\n새 작가 등록으로 이미지와 태그를 모아 보세요`;grid.append(empty);return;}
for(const e of list){const card=document.createElement('article');card.className='plus-card';card.dataset.id=e.id;const media=document.createElement('div');media.className='plus-media';const photo=button('','plus-photo',()=>openViewer(e.id),e.tag+' 이미지 크게 보기');const img=document.createElement('img');img.loading='lazy';img.draggable=false;img.alt=e.tag+' 참고 이미지';const {i,image}=imageAt(e);img.src=objectURL(image.blob);photo.append(img);media.append(photo);const counter=document.createElement('span');counter.className='plus-index';counter.textContent=`${i+1} / ${e.images.length}`;media.append(counter);if(e.images.length>1){media.append(button('‹','plus-nav plus-prev',()=>rotate(e.id,-1),'이전 이미지'),button('›','plus-nav plus-next',()=>rotate(e.id,1),'다음 이미지'));}let start;media.addEventListener('pointerdown',ev=>{start={x:ev.clientX,y:ev.clientY};});media.addEventListener('pointerup',ev=>{if(!start)return;const dx=ev.clientX-start.x,dy=ev.clientY-start.y;start=null;if(Math.abs(dx)>40&&Math.abs(dx)>Math.abs(dy)){rotate(e.id,dx<0?1:-1);photo.onclick=null;setTimeout(()=>photo.onclick=()=>openViewer(e.id),250);}});media.addEventListener('pointercancel',()=>start=null);
const body=document.createElement('div');body.className='plus-card-body';const tag=document.createElement('p');tag.className='plus-tag';tag.textContent=e.tag;const actions=document.createElement('div');actions.className='plus-card-actions';actions.append(button('태그 복사','',async()=>{try{await navigator.clipboard.writeText(e.tag);message('태그 복사됨');}catch{$('plusError').textContent='클립보드 접근이 차단됨 · 편집에서 태그를 선택해 복사해 주세요';}}),button('편집','',()=>{if(!busy)edit(e);}));body.append(tag,actions);card.append(media,body);grid.append(card);}}
function edit(e){draft=e?{...e,images:e.images.map(i=>({...i}))}:{id:uid(),version,tag:'',images:[],createdAt:Date.now()};$('plusEditorTitle').textContent=e?'작가 편집':'새 작가 등록';$('plusVersion').value=draft.version;$('plusTag').value=draft.tag;$('plusEditError').textContent='';$('plusSave').disabled=false;$('plusImages').disabled=false;imageReads=0;renderThumbs();let del=$('plusDelete');if(!del){del=button('작가 삭제','btn danger',removeEntry);del.id='plusDelete';$('plusForm').querySelector('.actions').prepend(del);}del.hidden=!e;$('plusEditor').showModal();$('plusTag').focus();}
let thumbURLs=[];
function renderThumbs(){thumbURLs.forEach(URL.revokeObjectURL);thumbURLs=[];$('plusThumbs').replaceChildren();draft.images.forEach((im,i)=>{const box=document.createElement('div');box.className='plus-thumb';const image=document.createElement('img');const url=URL.createObjectURL(im.blob);thumbURLs.push(url);image.src=url;image.alt=im.name||`이미지 ${i+1}`;const bar=document.createElement('div');bar.append(button(i===0?'대표':'대표로','',()=>{draft.images.unshift(draft.images.splice(i,1)[0]);renderThumbs();}),button('삭제','',()=>{draft.images.splice(i,1);renderThumbs();}));box.append(image,bar);$('plusThumbs').append(box);});}
async function validateImage(blob){if(!MIME.has(blob.type))throw new Error('지원하지 않는 이미지 형식입니다');if(blob.size>20*1024*1024)throw new Error('이미지는 장당 20MB 이하여야 합니다');if(!blob.size)throw new Error('빈 이미지 파일입니다');const url=URL.createObjectURL(blob);try{const img=new Image();img.src=url;await img.decode();if(!img.naturalWidth)throw Error();}catch{throw new Error('읽을 수 없는 이미지 파일입니다');}finally{URL.revokeObjectURL(url);}}
$('plusImages').onchange=async ev=>{const files=[...ev.target.files];ev.target.value='';const current=draft;imageReads++;$('plusSave').disabled=true;$('plusImages').disabled=true;$('plusEditError').textContent='이미지 확인 중…';try{const added=[];for(const f of files){await validateImage(f);added.push({id:uid(),name:f.name,blob:f});}if(draft===current&&$('plusEditor').open){draft.images.push(...added);renderThumbs();$('plusEditError').textContent='';}}catch(e){if(draft===current)$('plusEditError').textContent=errorText(e);}finally{if(draft===current){imageReads--;$('plusSave').disabled=imageReads>0;$('plusImages').disabled=false;}}};
$('plusForm').onsubmit=async ev=>{ev.preventDefault();if(busy||imageReads)return;const tag=$('plusTag').value.trim();if(!tag||!draft.images.length){$('plusEditError').textContent=!tag?'작가 태그를 입력해 주세요':'이미지를 한 장 이상 등록해 주세요';return;}const record={...draft,tag,version:$('plusVersion').value,updatedAt:Date.now()};lock(true);$('plusSave').disabled=true;$('plusCancel').disabled=true;$('plusDelete').disabled=true;try{await write(store=>store.put(record));entries=await readAll();setVersion(record.version);$('plusEditor').close();message('작가 저장됨');}catch(e){$('plusEditError').textContent=errorText(e);}finally{lock(false);$('plusSave').disabled=false;$('plusCancel').disabled=false;$('plusDelete').disabled=false;}};
async function removeEntry(){if(busy||!confirm('이 작가의 태그와 등록 이미지를 삭제할까요?'))return;lock(true);try{await write(store=>store.delete(draft.id));entries=await readAll();$('plusEditor').close();render();message('작가 삭제됨');}catch(e){$('plusEditError').textContent=errorText(e);}finally{lock(false);}}
$('plusEditor').addEventListener('cancel',e=>{if(busy)e.preventDefault();});$('plusEditor').addEventListener('close',()=>{thumbURLs.forEach(URL.revokeObjectURL);thumbURLs=[];draft=null;});$('plusCancel').onclick=()=>{if(!busy)$('plusEditor').close();};$('plusAdd').onclick=()=>edit(null);
function setVersion(v){version=v;document.querySelectorAll('[data-plus-version]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.plusVersion===v)));render();}
for(const b of document.querySelectorAll('[data-plus-version]'))b.onclick=()=>setVersion(b.dataset.plusVersion);
$('plusSearch').oninput=render;
function openViewer(id){viewerId=id;showViewerImage();$('plusViewer').showModal();}
function showViewerImage(){const e=selected(viewerId);if(!e)return;const {i,image}=imageAt(e);$('plusViewerTag').textContent=e.version+' · '+e.tag;$('plusViewerImage').src=objectURL(image.blob);$('plusViewerImage').alt=e.tag+' 참고 이미지';$('plusViewerCount').textContent=`${i+1} / ${e.images.length}`;$('plusViewerPrev').disabled=$('plusViewerNext').disabled=e.images.length===1;}
$('plusViewerPrev').onclick=()=>rotate(viewerId,-1);$('plusViewerNext').onclick=()=>rotate(viewerId,1);$('plusViewerClose').onclick=()=>$('plusViewer').close();$('plusViewer').onkeydown=e=>{if(e.key==='ArrowLeft'){e.preventDefault();rotate(viewerId,-1);}if(e.key==='ArrowRight'){e.preventDefault();rotate(viewerId,1);}};
const toDataURL=blob=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(blob);});
$('plusExport').onclick=async()=>{if(busy)return;lock(true);$('plusError').textContent='';try{const all=await readAll(),records=[];for(const e of all){const images=[];for(const im of e.images)images.push({id:im.id,name:im.name,data:await toDataURL(im.blob)});records.push({...e,images});}const blob=new Blob([JSON.stringify({format:'dust-artist-plus',version:1,exportedAt:new Date().toISOString(),entries:records})],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='dust-artist-plus-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);message('4.5 · 5 전체 백업 저장됨');}catch(e){$('plusError').textContent=errorText(e);}finally{lock(false);}};
async function parseBackup(file){const data=JSON.parse(await file.text());if(data?.format!=='dust-artist-plus'||data.version!==1||!Array.isArray(data.entries))throw new Error('Artist Tags + 백업 파일이 아닙니다');const ids=new Set(),out=[];for(const e of data.entries){if(!e||typeof e.id!=='string'||!/^[a-zA-Z0-9-]{1,100}$/.test(e.id)||ids.has(e.id)||!versions.includes(e.version)||typeof e.tag!=='string'||!e.tag.trim()||e.tag.length>2000||!Array.isArray(e.images)||!e.images.length)throw new Error('백업의 작가 정보가 올바르지 않습니다');ids.add(e.id);const images=[];for(const im of e.images){if(typeof im?.data!=='string')throw new Error('백업 이미지가 올바르지 않습니다');const m=/^data:(image\/(?:png|jpeg|webp|gif|avif));base64,([A-Za-z0-9+/]*={0,2})$/.exec(im.data);if(!m||m[2].length>28*1024*1024)throw new Error('백업 이미지 형식이나 크기가 올바르지 않습니다');const binary=atob(m[2]),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const blob=new Blob([bytes],{type:m[1]});await validateImage(blob);images.push({id:uid(),name:typeof im.name==='string'?im.name.slice(0,500):'image',blob});}out.push({id:e.id,version:e.version,tag:e.tag.trim(),images,createdAt:Number.isFinite(e.createdAt)?e.createdAt:Date.now(),updatedAt:Number.isFinite(e.updatedAt)?e.updatedAt:Date.now()});}return out;}
$('plusImport').onclick=()=>$('plusBackupFile').click();$('plusBackupFile').onchange=async ev=>{const file=ev.target.files[0];ev.target.value='';if(!file||busy)return;lock(true);$('plusError').textContent='백업 확인 중…';try{pending=await parseBackup(file);$('plusImportSummary').textContent=`4.5 ${pending.filter(e=>e.version==='4.5').length}명 · 5 ${pending.filter(e=>e.version==='5').length}명 · 이미지 ${pending.reduce((n,e)=>n+e.images.length,0)}장`;$('plusError').textContent='';$('plusImportDialog').showModal();}catch(e){pending=null;$('plusError').textContent=errorText(e);}finally{lock(false);}};
async function importEntries(replace){if(busy||!pending)return;if(replace&&!confirm('4.5와 5의 모든 카드를 백업 내용으로 교체합니다. 계속할까요?'))return;lock(true);try{await write(store=>{if(replace)store.clear();for(const e of pending){if(replace)store.put(e);else{const req=store.get(e.id);req.onsuccess=()=>{if(!req.result)store.put(e);};}}});entries=await readAll();positions.clear();render();$('plusImportDialog').close();pending=null;message(replace?'전체 복원 완료':'목록 추가 완료');}catch(e){$('plusError').textContent=errorText(e);$('plusImportDialog').close();}finally{lock(false);}}
$('plusMerge').onclick=()=>importEntries(false);$('plusReplace').onclick=()=>importEntries(true);$('plusImportCancel').onclick=()=>{$('plusImportDialog').close();pending=null;};$('plusImportDialog').addEventListener('cancel',e=>{if(busy)e.preventDefault();else pending=null;});
(async()=>{try{db=await openDB();db.onversionchange=()=>db.close();entries=await readAll();render();lock(false);}catch(e){$('plusError').textContent='로컬 저장소를 열지 못했습니다 · '+errorText(e);$('plusCount').textContent='저장소 접근 실패';}})();
})();
